### ISSUE TITLE
Unable to launch alfresco after applying alfresco-indexer-webscripts

### ISSUE THREAD

**Issue by ChalithaUdara** [maoo/alfresco-indexer#6]
Hi,
I cannot properly start alfresco server after applying alfresco-indexer-webscripts amp file. Alfresco gives the following error,

2015-10-23 10:34:09,115  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'indexingSqlSessionFactory' defined in class path resource [alfresco/module/alfresco-indexer-webscripts/context/service-context.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'useLocalCaches' of bean class [org.alfresco.ibatis.HierarchicalSqlSessionFactoryBean]: Bean property 'useLocalCaches' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1454)

Simply commenting out the 'useLocalCaches' caches property in service-context.xml fixes this. 
  <bean id="indexingSqlSessionFactory" class="org.alfresco.ibatis.HierarchicalSqlSessionFactoryBean">

    <property name="resourceLoader" ref="dialectResourceLoader"/>
    <property name="dataSource" ref="dataSource"/>
    <property name="configLocation">
      <value>classpath:alfresco/ibatis/alfresco-indexing-SqlMapConfig.xml</value>
    </property>
  </bean>

but I am not sure whether this properly fix this issue or will it introduce new issues.

I am using Alfresco enterprise edition 5.0.1

I would greatly appreciate if you can give a proper solution for this issue.

Thanks

**Comment by maoo** [comment]
can we close this?

**Comment by ChalithaUdara** [comment]
Yes, we can close this.

Thanks
